# Generated by Django 5.2 on 2025-04-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escorts', '0023_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('escort_phone', models.CharField(max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.IntegerField(null=True)),
                ('account_reference', models.CharField(max_length=12, null=True)),
                ('escort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='escorts.escort')),
            ],
        ),
    ]
