# Generated by Django 5.2 on 2025-07-23 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=4000, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_reference', models.CharField(blank=True, max_length=12, null=True)),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='escorts.escort')),
            ],
        ),
    ]
