# Generated by Django 5.2 on 2025-06-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='escort_id',
            new_name='escort',
        ),
    ]
