# Generated by Django 5.2 on 2025-06-28 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_rename_escort_id_payment_escort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='escort_phone',
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.IntegerField(default=datetime.date(2025, 6, 28), null=True),
        ),
    ]
