# Generated by Django 5.2 on 2025-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_remove_payment_escort_phone_alter_payment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.CharField(blank=True, default='now', null=True),
        ),
    ]
