# Generated by Django 5.2 on 2025-07-02 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('skin_color', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('body_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('escort_class', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_field', models.FileField(null=True, upload_to='images/')),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='escorts.escort')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_field', models.FileField(null=True, upload_to='profile_pics/')),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='escorts.escort')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='escorts.escort')),
            ],
        ),
    ]
