# Generated by Django 5.2 on 2025-07-23 07:31

import django.db.models.deletion
import escorts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', escorts.models.LowercaseTextField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('name', escorts.models.LowercaseTextField(max_length=50)),
                ('gender', escorts.models.LowercaseTextField(max_length=20)),
                ('age', models.IntegerField()),
                ('location', escorts.models.LowercaseTextField(max_length=50)),
                ('address', escorts.models.LowercaseTextField(default=None, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('skin_color', escorts.models.LowercaseTextField(default='chocolate', max_length=100, null=True)),
                ('body_type', escorts.models.LowercaseTextField(blank=True, default='curvy', max_length=100, null=True)),
                ('escort_class', escorts.models.LowercaseTextField(blank=True, default='vip', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('bio', models.TextField(default=None, max_length=110, null=True)),
                ('county', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escorts', to='escorts.county')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escorts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_field', models.FileField(null=True, upload_to='images/')),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='escorts.escort')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_field', models.FileField(null=True, upload_to='profile_pics/')),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='escorts.escort')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', escorts.models.LowercaseTextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='escorts.escort')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', escorts.models.LowercaseTextField(max_length=50)),
                ('county', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='escorts.county')),
            ],
        ),
        migrations.AddField(
            model_name='escort',
            name='town',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escorts', to='escorts.town'),
        ),
    ]
