# Generated by Django 5.2 on 2025-04-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escort',
            name='id',
        ),
        migrations.AlterField(
            model_name='escort',
            name='phone_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
