# Generated by Django 5.2 on 2025-07-26 20:30

import escorts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='address',
            field=escorts.models.LowercaseTextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
