# Generated by Django 5.2 on 2025-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
