# Generated by Django 5.2 on 2025-04-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0002_remove_escort_id_alter_escort_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escort',
            old_name='name',
            new_name='user_name',
        ),
    ]
