# Generated by Django 5.2 on 2025-07-19 21:20

import escorts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0002_escort_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='escort_id',
            new_name='escort',
        ),
        migrations.AlterField(
            model_name='escort',
            name='body_type',
            field=escorts.models.LowercaseTextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='escort_class',
            field=escorts.models.LowercaseTextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='gender',
            field=escorts.models.LowercaseTextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='escort',
            name='location',
            field=escorts.models.LowercaseTextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='escort',
            name='name',
            field=escorts.models.LowercaseTextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='escort',
            name='skin_color',
            field=escorts.models.LowercaseTextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=escorts.models.LowercaseTextField(max_length=100),
        ),
    ]
