# Generated by Django 5.2 on 2025-04-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0003_rename_name_escort_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_name', models.CharField(max_length=100)),
                ('agency_phone_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('agency_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='escort',
            name='created_by',
        ),
        migrations.AddField(
            model_name='escort',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.agency'),
        ),
    ]
