# Generated by Django 5.2 on 2025-07-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0003_rename_escort_id_service_escort_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='escort_id',
            new_name='escort',
        ),
    ]
