# Generated by Django 5.2 on 2025-07-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0003_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escorts', to='escorts.county'),
        ),
    ]
