# Generated by Django 5.2 on 2025-07-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0004_rename_escort_id_image_escort'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='bio',
            field=models.TextField(blank=True, max_length=110, null=True),
        ),
    ]
