# Generated by Django 5.2 on 2025-04-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0004_agency_remove_escort_created_by_escort_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escort',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='email',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='escort',
            name='agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escorts', to='escorts.agency'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='escorts.escort')),
            ],
        ),
    ]
