# Generated by Django 5.2 on 2025-07-22 12:09

import django.db.models.deletion
import escorts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0005_escort_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', escorts.models.LowercaseTextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', escorts.models.LowercaseTextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='escort',
            name='address',
            field=escorts.models.LowercaseTextField(default='nairobi,nairobi,nairobi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='bio',
            field=models.TextField(default=None, max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='body_type',
            field=escorts.models.LowercaseTextField(blank=True, default='curvy', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escort',
            name='escort_class',
            field=escorts.models.LowercaseTextField(blank=True, default='vip', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='skin_color',
            field=escorts.models.LowercaseTextField(default='chocolate', max_length=100, null=True),
        ),
    ]
