# Generated by Django 5.2 on 2025-07-22 19:49

import escorts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0006_county_town_escort_address_alter_escort_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='address',
            field=escorts.models.LowercaseTextField(default='County,Town,Area', max_length=100, null=True),
        ),
    ]
