# Generated by Django 5.2 on 2025-04-12 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0006_rename_escort_image_escort_id_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='escorts.escort')),
            ],
        ),
    ]
