# Generated by Django 5.2 on 2025-04-13 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0007_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escort',
            name='agency_id',
        ),
        migrations.RenameField(
            model_name='escort',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='escort',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
