# Generated by Django 5.2 on 2025-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0008_remove_escort_agency_id_rename_user_name_escort_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='body_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escort',
            name='skin_color',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
