# Generated by Django 5.2 on 2025-04-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0010_remove_image_id_remove_service_id_image_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='escort_class',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
