# Generated by Django 5.2 on 2025-04-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0011_escort_escort_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_field',
            field=models.FileField(null=True, upload_to='media/images/'),
        ),
    ]
