# Generated by Django 5.2 on 2025-04-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0012_remove_image_image_image_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
