# Generated by Django 5.2 on 2025-04-16 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0013_alter_image_image_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePics',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_field', models.FileField(null=True, upload_to='profile_pics/')),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='escorts.escort')),
            ],
        ),
    ]
