# Generated by Django 5.2 on 2025-04-16 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0014_profilepics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePics',
            new_name='ProfilePicture',
        ),
    ]
