# Generated by Django 5.2 on 2025-04-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0015_rename_profilepics_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='escort_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escort',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
