# Generated by Django 5.2 on 2025-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0016_escort_escort_id_alter_escort_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escort',
            name='escort_id',
        ),
        migrations.AlterField(
            model_name='escort',
            name='phone_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
