# Generated by Django 5.2 on 2025-04-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0018_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amout',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
