# Generated by Django 5.2 on 2025-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0021_alter_payment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_reference',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
