# Generated by Django 5.2 on 2025-04-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0022_payment_account_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
